--- #YAML:1.0
name:               Win32-MSI-HighLevel
version:            1.0006
abstract:           Perl wrapper for Windows Installer API
author:
    - Peter Jaquiery (grandpa@cpan.org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Win32::API:  0.46
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
