# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Win32-MSI-HighLevel
version:      1.0001
version_from: lib/Win32/MSI/HighLevel.pm
installdirs:  site
requires:
    Win32::API:                    0.46

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
