--- #YAML:1.0
name:                Win32-MSI-HighLevel
version:             1.0002
abstract:            Perl wrapper for Windows Installer API
license:             ~
author:              
    - Peter Jaquiery (grandpa@cpan.org)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::Pod:                     0
    Test::Pod::Coverage:           0
    Win32::API:                    0.46
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
