--- #YAML:1.0
name:               Win32-MSI-HighLevel
version:            1.0005
abstract:           Perl wrapper for Windows Installer API
author:
    - Peter Jaquiery (grandpa@cpan.org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::Pod:            0
    Test::Pod::Coverage:  0
    Win32::API:           0.46
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
